# CI de Nivel 01 - Disparo manual - Execucao de testes JavaScript com Mocha

# nome do nosso 'pipeline'
name: 'Execuçao Manual - pipeline de testes JS'

# regras de disparo (gatilhos/triggers)
# gatilho de exec manual = workflow_dispatch

on:
  workflow_dispatch:

# trabalhos ou tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:
    #maquina que o job vai executar
    runs-on: ubuntu-latest

    # passos do script de build (steps)
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalaçao do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalaçao das dependencias
      - name: Instalando dependencias
        run: npm install

      # instalaçao dos testes e2e com Mochawesome
      - name: Executando Testes E2E com Mochawesome
        run: npx mocha testes/01-testes.js

      - name: Upload do Relatório Mochawesome
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: mochawesome-report
          path: mochawesome-report
